[workspace]
members = ["core", "server"]

[workspace.dependencies]
anyhow = "1.0.100"
crc32fast = "1.5.0"
tokio = { version = "1.48.0", features = ["full"]}
log = "0.4.29"
clap = { version = "4.5.53", features = ["derive"]}
env_logger = "0.11.8"
