[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
core = {path = "../core"}
tokio.workspace = true
anyhow.workspace = true
log.workspace = true
clap.workspace = true
env_logger.workspace = true
openraft.workspace = true
actix-web.workspace = true
